### ISSUE TITLE
TODO before make it public

### ISSUE THREAD

**Issue by nikivazou** [nikivazou/EquationalReasoningInLiquidHaskell#1]
- [ ] merge https://github.com/ucsd-progsys/liquidhaskell/pull/1327 and update server
- [ ] make demo use the online serve
- [ ] add subsections to the `.lhs` files
- [ ] update paper with the link for source & proof-combinators
